[project]
name = "yolo-app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dronekit>=2.9.2",
    "future>=1.0.0",
    "pymavlink>=2.4.49",
    "torch>=2.9.1",
    "ultralytics>=8.4.6",
]
